---
# Backtesting

In [5]:
import pandas as pd
import numpy as np

def padding(x):
    x = str(x)
    return x.rjust(6, "0")

In [6]:
df_전처리끝 = pd.read_csv("./datasets/df_부실징후_전처리끝.csv", index_col=0)
df_전처리끝["거래소코드"] = df_전처리끝["거래소코드"].map(padding)
df_전처리끝

,회사명,거래소코드,회계년도,회생여부,이자보상배율(이자비용),부가가치(백만원),금융비용(백만원),매출액총이익률,매출액순이익률,총자본사업이익률,...,LEV지수,KZ지수,WW지수,CL지수,NCAV지수,기업생명주기,순매수거래량_기관,순매수거래대금 비중_기관,순매수거래량_외국인,순매수거래대금 비중_외국인
0,케이알모터스(주),000040,2013,0,-4.29,9379.15,603.89,7.59,-6.64,-2.77,...,0.000000,-8.591876e+10,-6.576044e+08,2.809350e+11,0.001550,1,154.0,0.000010,666080.0,0.001283
1,(주)삼양홀딩스,000070,2013,1,0.14,196611.70,-1765.62,13.02,-1.13,0.83,...,0.071968,-2.442820e+11,1.183926e+09,1.337212e+11,0.099707,4,102250.0,0.002022,-91060.0,-0.001833
2,(주)두산,000150,2015,1,0.38,574662.07,45660.54,15.78,-8.97,1.01,...,0.088465,-2.081378e+11,1.459636e+09,2.011217e+11,-0.786424,0,-426231.0,-0.001261,-625687.0,-0.004927
3,성창기업지주(주),000180,2013,0,-1.39,28423.83,1111.80,14.62,-2.82,-0.52,...,0.078762,-4.619692e+10,2.632381e+09,1.809579e+11,0.106379,0,28438.0,0.001337,-43268.0,0.000147
4,성창기업지주(주),000180,2016,0,0.62,56531.73,841.14,15.83,11.64,0.34,...,0.034395,-9.480783e+10,3.381700e+07,-2.535962e+11,-0.137771,2,671474.0,0.001637,819639.0,0.002100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,(주)더코디,224060,2017,0,-1.59,6801.41,1798.06,11.31,-5.51,-4.72,...,0.000344,-2.930855e+11,1.082427e+09,4.233479e+11,0.207267,0,-5558666.0,-0.005950,-503444.0,-0.000885
1297,(주)아이엠텍,226350,2018,0,-6.35,6328.81,639.05,29.93,-229.61,-11.58,...,0.092196,-1.872540e+11,8.426451e+09,7.823447e+12,-0.559426,0,-15421.0,-0.000185,285835.0,0.000957
1298,(주)오스테오닉,226400,2018,0,0.19,-1214.53,527.75,43.11,-73.05,0.87,...,0.046767,-2.930819e+11,4.567604e+08,2.716222e+12,0.411318,1,-7292.0,-0.000270,10819.0,0.000159
1299,자이글(주),234920,2018,0,-14.09,-469.47,71.75,69.74,-11.18,-6.58,...,0.000000,-3.624483e+10,6.277626e+09,4.972630e+11,0.183399,0,-84982.0,-0.001042,162700.0,0.000741
1300,(주)클리오,237880,2018,1,-0.35,37456.28,1507.51,56.38,0.53,0.69,...,0.000000,-6.642425e+10,-3.002447e+10,1.131726e+11,0.286130,2,216248.0,0.002196,-520799.0,0.000177

In [7]:
df_실제회생기업 = df_전처리끝[df_전처리끝["회생여부"]==1][["회사명","거래소코드","회계년도","기업생명주기"]].sort_values(by="회계년도", ascending=True)
df_실제회생기업

                회사명   거래소코드  회계년도  기업생명주기
1          (주)삼양홀딩스  000070  2013       4
494    (주)에스에프에이반도체  036540  2013       1
492   에스케이 머티리얼즈(주)  036490  2013       2
487        (주)이지홀딩스  035810  2013       1
477        신세계건설(주)  034300  2013       1
...             ...     ...   ...     ...
574           KD(주)  044180  2018       4
603      유니온머티리얼(주)  047400  2018       0
1294       하이즈항공(주)  221840  2018       3
463        (주)동성화인텍  033500  2018       3
1300         (주)클리오  237880  2018       2

[480 rows x 4 columns]

In [8]:
df_실제회생기업.to_csv("./datasets/실제회생기업.csv")